### ISSUE TITLE
WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally

### ISSUE THREAD

**Issue by GrayXu** [misaka7690/HUST-2019-ncov-submit-fucker#2]
```
Traceback (most recent call last):
  File "fucker.py", line 127, in <module>
    result = post_fuck_action(t1,t2)
  File "fucker.py", line 64, in post_fuck_action
    driver = webdriver.Chrome(executable_path='./chromedriver',chrome_options=options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.4.0-93-generic x86_64)
```

Ubuntu 16, selenium (3.141.0), py 2.7.12.   
I know little about selenium, but it seems like this chrome isn't on headless mode?

I fixed it with replace `options.headless = True` with 
```
options.add_argument('--headless')
options.add_argument('--no-sandbox')
```

Any ideas?

btw, using crontab may be better?

**Comment by misaka7690** [comment]
嗯,你自己看着改吧😂
因为这个仓库就是和服务器上的代码环境一致的,所以改起来有点麻烦(隐私方面),已经没时间折腾了
